<a href="https://colab.research.google.com/github/sharatg9/Deep-Learning-ML-algorithm-using-pytorch/blob/master/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl 


     |████████████████████████████████| 592.3MB 3.2MB/s 
ERROR: torchvision 0.4.0 has requirement torch==1.2.0, but you'll have torch 0.3.0.post4 which is incompatible.
ERROR: fastai 1.0.58 has requirement torch>=1.0.0, but you'll have torch 0.3.0.post4 which is incompatible.
  Found existing installation: torch 1.2.0
    Uninstalling torch-1.2.0:
      Successfully uninstalled torch-1.2.0


In [0]:
!pip3 install torchvision

     |████████████████████████████████| 748.9MB 27kB/s 
  Found existing installation: torch 0.3.0.post4
    Uninstalling torch-0.3.0.post4:
      Successfully uninstalled torch-0.3.0.post4


In [0]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import numpy as np

x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1, 1)

y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1, 1)


class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)  
    
    def forward(self, x):
        out = self.linear(x)
        return out

input_dim = 1
output_dim = 1

model = LinearRegressionModel(input_dim, output_dim)

criterion = nn.MSELoss()

learning_rate = 0.01

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

train model 

In [0]:
epoch = 100 

for i in range(epoch):
  inputs = Variable(torch.from_numpy(x_train))
  labels = Variable(torch.from_numpy(y_train))
  
  optimizer.zero_grad()
  
  output = model(inputs)
  
  loss = criterion(output, labels)
  
  loss.backward()
  
  optimizer.step()
  
  print('epoch {}, loss {}'.format(epoch, loss.item()))
  
 
  
  

Predication

In [40]:
with torch.no_grad():

  x_train_predict = Variable(torch.from_numpy(x_train))

  print(x_train_predict)

  Test_Data = 20
  Test_Data = np.array(Test_Data, dtype=np.float32)
  Test_Data = Test_Data.reshape(-1, 1)
  Test_Data = Variable(torch.from_numpy(Test_Data))
  
  print(Test_Data)
  
  predicted = model(Test_Data)
  
  

  print(predicted)

tensor([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
tensor([[20.]])
tensor([[41.0649]])
