<a href="https://colab.research.google.com/github/sharatg9/Deep-Learning-ML-algorithm-using-pytorch/blob/master/numpy_array_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#creating array from list using data type as float

import numpy as np

a = np.array([[1,2,3],[3,5,6],[5,9,8]], dtype = 'float')
print(a)




In [0]:
#creating array object 
#printing its data type


a = np.array([[1,2,3],[2,3,6],[4,5,6],[5,6,6]])
print(type(a))

print("array shape ", a.shape)

print("size of array", a.size)

print("data type by default", a.dtype)


# Array in numpy


*   arr.ndim
*   arr.dtype
*   arr.size
*   arr.shape



In [17]:
#creating a 3*3 array with zeros

a = np.zeros([3,3])
print(a)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# Array with random number

a = np.random.random([2,2])
print(a)



[[0.50570694 0.62983584]
 [0.0554514  0.45805864]]


In [36]:
# sequence array with 0 to 30 with step of 5

b = np.arange(0,30,5)
print(b)

# sequence array of 8 in range of 0 to 5

c = np.linspace(1,5,8)
print(c)


[ 0  5 10 15 20 25]
[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]


In [0]:
#reshaping array 

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("original", a)

new_a = a.reshape(-1,1)
print("reshape", new_a)


In [56]:
# Flatten array 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
flarr = arr.flatten()


print ("\nOriginal array:\n", arr) 
print ("Fattened array:\n", flarr) 


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


# array creation

1.   np.array([1,2],[2,3])
2.   np.zeros(2,2)
3.   np.random.random([2,2])
4.   np.arrange(0,30,5)
5.   np.linspace(0,5,10)
6.   array.reshape(-1,1)
7.   array.flatten()


  
    



In [57]:
arr = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]])

print(arr)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [82]:
a = arr[:3, ::2 ]
print(arr)

print("------------------------------")

b = arr[[0,1,2,3],[3,2,1,0]]
# indices (0,3) = 4 and (1,2) = 6 and so on                   
                   
print(b)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
------------------------------
[4. 6. 0. 3.]


In [87]:
c = arr[arr>0]

print(c)

[2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [90]:
# Basic operations

a = np.array([1,2,3,4])

print(a)

print("add", a+1)

print("sub", a-1)

print("mul", a*10)

print("expo", a**2)


[1 2 3 4]
add [2 3 4 5]
sub [0 1 2 3]
mul [10 20 30 40]
expo [ 1  4  9 16]


In [93]:
# array transport


a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

print(a.T)




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [100]:
#maximum and minimum 

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("largest", a.max())

print("largest", a.max(axis=1))

print("smallest", a.min())

print("sum", a.sum())



largest 9
largest [3 6 9]
smallest 1
avg 45


#Array Operations


1.   array.T
2.   array.max()
1.   array.min()
2.   array.sum()
1.   a + b addition
2.   a * b elementary multiplicatio
3.   a.dot(b) mat multiplication 



In [103]:
a = np.random.random([2,2])
print(a)

[[0.69808401 0.76557935]
 [0.46898949 0.3637444 ]]


In [104]:
#sorting 

a = np.array([[1, 4, 2], 
                 [3, 4, 6], 
              [0, -1, 5]])
print(a)



[[ 1  4  2]
 [ 3  4  6]
 [ 0 -1  5]]


In [112]:
print(np.sort(a))  # by defulat axis = 1

print(np.sort(a, axis= None))

print(np.sort(a, axis = 0))

#merge sort algorithm 

print(np.sort(a, axis = None, kind='mergesort'))



[[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
[-1  0  1  2  3  4  4  5  6]
[[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]
[-1  0  1  2  3  4  4  5  6]


In [117]:
dtypes = [('name', 'S10')]
values = [("sharat"), ("bhagya")]

arr = np.array(values, dtype = dtypes)
print(arr)

print(np.sort(arr, order='name'))


[(b'sharat',) (b'bhagya',)]
[(b'bhagya',) (b'sharat',)]
