<a href="https://colab.research.google.com/github/sharatg9/Deep-Learning-ML-algorithm-using-pytorch/blob/master/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import torch

#crearting numpy array
a = np.array([1,2,3])
print(a)

#creating tensors
b = torch.tensor([1,2,3])
print(b)

#converting numpy array to tensor
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = torch.from_numpy(arr)
print(c)

#converting tensor to numpy array
arr_new = c.numpy()              
print(arr_new)

#reshapping tensors
c = c.reshape(-1,1)
print(c)




[1 2 3]
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
[[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [25]:
#x_array = [i for i in range(10)]  
x_train = np.array([i for i in range(10)], dtype="float") 
x_train = torch.from_numpy(x_train)
#inputs
print(x_train) 


#y_array  y = 2x+1 
y_train = np.array([2*i+1 for i in range(10)], dtype="float")
y_train = torch.from_numpy(y_train)
#lable
print(y_train)

y1_train = np.random.random([2,2])
y1_train = torch.from_numpy(y1_train)
print(y1_train)





tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
tensor([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=torch.float64)
tensor([[0.4958, 0.5717],
        [0.5568, 0.5520]], dtype=torch.float64)


In [0]:
np.zeros([2,2])

In [0]:
torch.zeros([2,2])

In [39]:
a = np.random.random([2,2])
print("numpy random arraya", a)

b = torch.rand(2,2)
print("random", b)


numpy random arraya [[0.99523647 0.22217838]
 [0.79447672 0.75109473]]
random tensor([[0.5327, 0.0859],
        [0.3771, 0.6173]])


In [58]:
#seeds reproduaibility 
#seed number doesn't matter

a = np.random.seed(2)
a = np.random.rand(2,2)
print(a)

b = np.random.seed(2)
b = np.random.rand(2,2)
print(b)

c = np.random.seed(2)
c = np.random.rand(2,2)
print(c)

#produce different array
d = np.random.rand(2,2)
print(d)


#tensor 
ta = torch.manual_seed(0)
ta = torch.rand(2,2)
print(ta)


tb = torch.manual_seed(0)
tb = torch.rand(2,2)
print(tb)


[[0.4359949  0.02592623]
 [0.54966248 0.43532239]]
[[0.4359949  0.02592623]
 [0.54966248 0.43532239]]
[[0.4359949  0.02592623]
 [0.54966248 0.43532239]]
[[0.4203678  0.33033482]
 [0.20464863 0.61927097]]
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])


# tensor Datatypes



1.   int64   - longTensor   
2.   int32   - IntTensor
1.   uint8   - ByteTensor 
2.   float64 - doubleTensor
1.   float32 - floatTensor   
2.   double  - doubleTensor



In [62]:
#tensor on CPU to GPU

tensor_cpu = torch.zeros(2,2)
if torch.cuda.is_available():
  tensor_cpu.cuda()
  print("cuda is avaiable")
else: 
  print("cuda is unavaiable")
  
  
#GPU to CPU  
tensor_cpu.cpu()  
  

cuda is unavaiable


In [76]:
#tensor arithmatic

a = torch.zeros(2,2)
print(a)

#resize
a.view(4 , 1)


b = torch.ones(2,2)
print(b)

c = torch.ones(2,2)
print(c)

d = torch.add(b,c)
print(d)

print("-"*25)

addA = torch.ones(2,2)

addB = torch.ones(2,2)

addA.add_(addB)

'''
  in place
  a.add_(b)
  a.sub_(b)
  a.mul_(b)
  a.div_(b)
  
  c = a+b
  c = a.add(a)

'''


tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
-------------------------


tensor([[2., 2.],
        [2., 2.]])

In [104]:
# tensor mean

with torch.no_grad(): 
  
  x = torch.tensor([[i for i in range(10)], [i*2 for i in range(10)]], dtype=float)

  print(x)



  b = x.max()
  d = x.min()
  c = x.sum()

  print("mean of", x.mean(dim=1))
  print("standard deviation of", x.std(dim=1))
  print("maximum item of", b )
  print("minimun item of", d )
  print("Sum of ", c)





tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]],
       dtype=torch.float64)
mean of tensor([4.5000, 9.0000], dtype=torch.float64)
standard deviation of tensor([3.0277, 6.0553], dtype=torch.float64)
maximum item of tensor(18., dtype=torch.float64)
minimun item of tensor(0., dtype=torch.float64)
Sum of  tensor(135., dtype=torch.float64)


In [121]:
# variables and gradients
'''
  
  variables accumalate gradients 
  
'''

from torch.autograd import Variable

varA = Variable(torch.ones(2,2), requires_grad = True)
varB = Variable(torch.ones(2,2), requires_grad = True)

print(varA.add(varB))


# Gradeint

'''
what excatly requires_grad?
allows calcultion of grad w.r.t to variable 

y = 5(x + 1)^2



'''

x = Variable(torch.ones(2), requires_grad = True)
y = 5 * (x+1) ** 2

#Reduce the y to scalar

'''
Summary 

where y = 20 , 20
where o = 20 after making that as scalar 
differnation of o using backward() and we will get 10

to access it x.grad which has diff of y ;


'''

o = 1/2 * torch.sum(y)
print(o)

#calculate gradient descent
o.backward()
x.grad[0]

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor(20., grad_fn=<MulBackward0>)


tensor(10.)